#!/bin/bash
# 演示 V2.1.0 的三个关键改进

set -euo pipefail

PY=${PY:-python}
DIR=$(cd "$(dirname "$0")/.." && pwd)
cd "$DIR"

echo "========================================================================"
echo "           QUBO Prover V2.1.0 - 新功能演示"
echo "========================================================================"
echo ""
echo "本脚本演示三个关键改进："
echo "  1. 完整 QUBO 方程展示"
echo "  2. 详细证明路径"
echo "  3. Modus Tollens 正确性验证"
echo ""
echo "========================================================================"
echo ""

# 改进 1: 展示完整 QUBO 方程
echo "【改进 1】展示完整 QUBO 方程"
echo "------------------------------------------------------------------------"
echo "命令: python -m qubo_prover_v2.cli --axioms \"P; P->Q\" --goal \"Q\" --show-qubo"
echo ""
$PY -m qubo_prover_v2.cli --axioms "P; P->Q" --goal "Q" --show-qubo --reads 100
echo ""
echo "✓ 可以看到完整的 QUBO 方程，包括线性项、二次项和常数项"
echo ""
echo "========================================================================"
echo ""
read -p "按 Enter 继续下一个演示..."
echo ""

# 改进 2: 详细证明路径
echo "【改进 2】详细证明路径"
echo "------------------------------------------------------------------------"
echo "命令: python -m qubo_prover_v2.cli --axioms \"P->Q; ~Q\" --goal \"~P\""
echo ""
$PY -m qubo_prover_v2.cli --axioms "P->Q; ~Q" --goal "~P" --reads 100
echo ""
echo "✓ 证明路径包含四个步骤："
echo "  步骤 1: 列出公理"
echo "  步骤 2: 显示命题变量赋值"
echo "  步骤 3: 详细推理过程（包括反证法）"
echo "  步骤 4: 最终结论"
echo ""
echo "========================================================================"
echo ""
read -p "按 Enter 继续下一个演示..."
echo ""

# 改进 3: Modus Tollens 正确性验证
echo "【改进 3】Modus Tollens 正确性验证"
echo "------------------------------------------------------------------------"
echo "Modus Tollens 是经典的推理规则："
echo "  公理 1: P→Q"
echo "  公理 2: ~Q"
echo "  结论: ~P"
echo ""
echo "逻辑推理："
echo "  假设 P=真，则由 P→Q 得 Q=真"
echo "  但 ~Q=真，即 Q=假，矛盾！"
echo "  因此 P=假，即 ~P=真"
echo ""
echo "真值表验证:"
echo "  P | Q | P->Q | ~Q | ~P | 满足公理? | 满足目标?"
echo "  0 | 0 |   1  |  1 |  1 |     ✓      |     ✓"
echo "  0 | 1 |   1  |  0 |  1 |     ✗      |     ✓"
echo "  1 | 0 |   0  |  1 |  0 |     ✗      |     ✗"
echo "  1 | 1 |   1  |  0 |  0 |     ✗      |     ✗"
echo ""
echo "只有 P=0, Q=0 同时满足所有公理和目标！"
echo ""
echo "现在运行系统验证:"
echo "------------------------------------------------------------------------"
$PY -m qubo_prover_v2.cli --axioms "P->Q; ~Q" --goal "~P" --reads 100
echo ""
echo "✓ 系统正确地证明了 Modus Tollens！"
echo ""
echo "========================================================================"
echo ""

# 总结
echo "【总结】"
echo "------------------------------------------------------------------------"
echo "V2.1.0 的三个关键改进全部展示完毕："
echo ""
echo "1. ✅ 完整 QUBO 方程展示"
echo "   - 使用 --show-qubo 参数"
echo "   - 清晰显示线性项、二次项和常数项"
echo "   - 帮助理解能量函数的构成"
echo ""
echo "2. ✅ 详细证明路径"
echo "   - 四步骤推理过程"
echo "   - 显示命题变量真值"
echo "   - 展示推理规则使用"
echo "   - 对 Modus Tollens 展示完整反证法"
echo ""
echo "3. ✅ Modus Tollens 正确性"
echo "   - 经典推理规则"
echo "   - 逻辑完全正确"
echo "   - 通过真值表验证"
echo "   - 系统正确实现"
echo ""
echo "========================================================================"
echo ""
echo "更多信息请查看:"
echo "  - README.md - 完整文档"
echo "  - IMPROVEMENTS.md - 改进详情"
echo "  - QUICKSTART.md - 快速入门"
echo ""
echo "========================================================================"

